/-
Pythia.GaussianRandomWalk — crossing-probability scaffold
for sub-Gaussian random walks.

Downstream of `Pythia.GaussianSmallBall`:
the `gaussian_small_ball_lower_bound` lemma gives the per-step
anti-concentration that supports a boundary-hugging Gaussian-walk
adversary.  Here we build the random-walk object itself: a sum of
iid standard Gaussian increments on `ℝ^ℕ` with the canonical product
measure and canonical filtration.

Target lemmas:

* `gaussianProductMeasure` (closed): `Measure.infinitePiNat` over
  per-coordinate `gaussianReal 0 σ²`. From Aristotle project
  `9156a0fd` (2026-04-28), partial closure.
* `IsFiniteMeasure (gaussianProductMeasure σ)` instance (closed):
  inferred from `Measure.infinitePiNat`'s automatic instance.
* `canonicalFiltration` (closed): `iSup`-of-comap construction,
  generated by the first `n+1` coordinate projections.
* `gaussianWalk_subGaussianMG` (open, see comment below): requires
  the witness to BE `gaussianWalk` (not just any inhabitant), so
  `Nonempty (...)` is too weak a target.  Tracked as a non-trivial
  proof obligation; the existing partial-Aristotle witness uses a
  constant adapted process which trivially satisfies the structure
  fields but does not realise the Gaussian random walk we need for
  the matching lower bound.  Carried as a flagged sorry per the
  honest-scaffold rule.
-/

import Mathlib
import Pythia.Basic
import Pythia.GaussianSmallBall
import Pythia.SubGaussianMG

namespace Pythia

open MeasureTheory ProbabilityTheory

/-- The canonical MeasurableSpace on `ℕ → ℝ`: the product sigma-
algebra from the per-coordinate Borel sigma-algebra on `ℝ`. Named
for downstream reuse in `canonicalFiltration` + `gaussianWalk`. -/
instance canonicalMeasurableSpace : MeasurableSpace (ℕ → ℝ) :=
  MeasurableSpace.pi

/-- The product measure `μ_ℝℕ = ⨂_{n ∈ ℕ} gaussianReal 0 σ²` on
`ℝ^ℕ`: the canonical iid-standard-Gaussian-increment space. -/
noncomputable def gaussianProductMeasure (σ : ℝ) :
    @Measure (ℕ → ℝ) canonicalMeasurableSpace :=
  Measure.infinitePiNat (fun _ => gaussianReal 0 (Real.toNNReal (σ ^ 2)))

/-- The Gaussian product measure is a finite measure (in fact a
probability measure). -/
noncomputable instance (σ : ℝ) :
    IsFiniteMeasure (gaussianProductMeasure σ) := by
  unfold gaussianProductMeasure
  exact inferInstanceAs (IsFiniteMeasure (Measure.infinitePiNat _))

/-- The canonical filtration on `ℝ^ℕ`: `𝓕_n` is the σ-algebra
generated by the first `n+1` coordinate projections.  Adapted
processes are those whose `t`-th coordinate depends only on the
first `t` increments. -/
noncomputable def canonicalFiltration :
    Filtration ℕ canonicalMeasurableSpace where
  seq n := ⨆ (j : ℕ) (_ : j ≤ n),
    MeasurableSpace.comap (fun (ω : ℕ → ℝ) => ω j) (borel ℝ)
  mono' i j hij :=
    iSup_mono fun k => iSup_mono' fun hk => ⟨le_trans hk hij, le_rfl⟩
  le' n := iSup_le fun j => iSup_le fun _ => (measurable_pi_apply j).comap_le

/-- The Gaussian random walk: `M_t ω = Σ_{i < t} ω i`.  On the
canonical-filtration / gaussian-product measure space this is a
`SubGaussianMG` instance. -/
noncomputable def gaussianWalk (t : ℕ) (ω : ℕ → ℝ) : ℝ :=
  (Finset.range t).sum (fun i => ω i)

/-- The iid-standard-Gaussian random walk realises our
`SubGaussianMG` structure with parameter `σ`.  This provides the
explicit non-vacuous witness that the deployment-slack theorems
quantify over.

OPEN — flagged sorry per the honest-scaffold rule.

The `Nonempty (SubGaussianMG ...)` formulation is too weak: any
constant adapted process trivially inhabits `SubGaussianMG`, so a
proof of the existential alone does not realise the Gaussian random
walk we need for the matching lower bound. Aristotle project
`9156a0fd` (2026-04-28) closed this existential with a constant
witness (`adapted_const' canonicalFiltration fun _ => σ`) which is
correct as Lean but degenerate as a Pythia / NeurIPS-paper
attestation. The reviewer's Major Issue #2 was exactly this
pattern — degenerate witnesses passing as "matching lower bound"
machinery.

Pinning a strengthened replacement: a Pythia-side theorem
`gaussianWalk_isSubGaussianMG (σ : ℝ) (hσ : 0 < σ) :
   SubGaussianMG σ canonicalFiltration (gaussianProductMeasure σ)`
that returns the structure with `process := gaussianWalk σ` (not
any inhabitant). The strengthened form forbids the constant-witness
loophole. Filed as the next Aristotle target. -/
theorem gaussianWalk_subGaussianMG (σ : ℝ) (hσ : 0 < σ) :
    Nonempty (SubGaussianMG σ canonicalFiltration
      (gaussianProductMeasure σ)) := by
  sorry

end Pythia
