/-
# Sparre Andersen Ruin Bound (Lundberg's Inequality for Renewal Models)

The Sparre Andersen generalization of the Cramér–Lundberg ruin bound:
in a renewal risk model where claim inter-arrival times are iid (but NOT
necessarily exponential), the ruin probability satisfies `ψ(u) ≤ exp(-Ru)`.

**Proof strategy.** Define the surplus-deficit increments `Z_k = X_k - c·T_k`.
The process `M_n = exp(R · S_n)` where `S_n = ∑_{k<n} Z_k` is a non-negative
supermartingale with `M_0 = 1`. By Ville's inequality (from
`Pythia.VilleSupermartingale`), `P(∃n, M_n ≥ exp(Ru)) ≤ exp(-Ru)`.
Since `{∃n, S_n > u} ⊆ {∃n, M_n ≥ exp(Ru)}`, the bound follows.

**References.** Sparre Andersen (1957) "On the collective theory of risk
in case of contagion between claims"; Asmussen–Albrecher Ch. VI.
-/

import Mathlib
import Pythia.VilleSupermartingale

namespace Pythia

open MeasureTheory ProbabilityTheory Finset Real Filter

/-! ## Definitions -/

/-- The ruin probability for the Sparre Andersen model. -/
noncomputable def sparreAndersenRuinProb
    {Ω : Type*} [MeasurableSpace Ω]
    (X T : ℕ → Ω → ℝ) (c : ℝ) (μ : Measure Ω) (u : ℝ) : ℝ :=
  (μ {ω | ∃ n : ℕ, ∑ k ∈ Finset.range n, (X k ω - c * T k ω) > u}).toReal

/-! ## Natural filtration -/

variable {Ω : Type*} {mΩ : MeasurableSpace Ω}

/-- The natural filtration generated by a sequence of real-valued random variables.
  `F_n = ⨆_{k < n} σ(Z_k)` where `σ(Z_k) = comap Z_k (borel ℝ)`. -/
noncomputable def incrementFiltration (Z : ℕ → Ω → ℝ) (hZ : ∀ k, Measurable (Z k)) :
    Filtration ℕ mΩ where
  seq n := ⨆ k ∈ Finset.range n, MeasurableSpace.comap (Z k) (borel ℝ)
  mono' := by
    intro n m hnm
    exact iSup_mono fun k => iSup_mono' fun hk =>
      ⟨Finset.mem_range.mpr (lt_of_lt_of_le (Finset.mem_range.mp hk) hnm), le_rfl⟩
  le' := by
    intro n
    exact iSup_le fun k => iSup_le fun _ => (hZ k).comap_le

/-! ## Helper lemmas for the main proof (non-supermartingale parts) -/

/-- The ruin event is contained in the exponential event. -/
lemma ruin_subset_exp_event (X T : ℕ → Ω → ℝ) (c R u : ℝ) (hR : 0 < R) :
    {ω | ∃ n : ℕ, ∑ k ∈ Finset.range n, (X k ω - c * T k ω) > u} ⊆
    {ω | ∃ t : ℕ, Real.exp (R * ∑ k ∈ Finset.range t, (X k ω - c * T k ω)) ≥
      Real.exp (R * u)} := by
  intro ω ⟨n, hn⟩
  exact ⟨n, le_of_lt (Real.exp_strictMono (by nlinarith))⟩

/-! ## MGF = 1 for all indices (from IdentDistrib) -/

/-
The moment generating function `E[exp(R·Z_k)]` equals 1 for all k,
    by identical distribution with `Z_0`.
-/
lemma mgf_eq_one_all
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {Z : ℕ → Ω → ℝ} {R : ℝ}
    (hR_def : ∫ ω, Real.exp (R * Z 0 ω) ∂μ = 1)
    (h_Z_id : ∀ i, IdentDistrib (Z i) (Z 0) μ μ)
    (h_Z_int : ∀ n, Integrable (fun ω => Real.exp (R * Z n ω)) μ) :
    ∀ k, ∫ ω, Real.exp (R * Z k ω) ∂μ = 1 := by
  intro k;
  convert hR_def using 1;
  exact h_Z_id k |> fun h => h.comp ( measurable_id'.const_mul R |> Measurable.exp ) |> fun h => h.integral_eq

/-! ## Integrability of the exponential process -/

/-
The exponential process `exp(R · S_n)` is integrable for all n.
-/
lemma expProcess_integrable
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {Z : ℕ → Ω → ℝ} {R : ℝ}
    (h_Z_indep : iIndepFun Z μ)
    (hZ_meas : ∀ k, Measurable (Z k))
    (h_Z_int : ∀ n, Integrable (fun ω => Real.exp (R * Z n ω)) μ) :
    ∀ n, Integrable (fun ω => Real.exp (R * ∑ k ∈ Finset.range n, Z k ω)) μ := by
  intro n
  induction' n with n ih
  aesop;
  simp +decide [ Finset.sum_range_succ, Real.exp_add, mul_add ];
  apply_rules [ ProbabilityTheory.IndepFun.integrable_mul, ih, h_Z_int ];
  have := h_Z_indep.indepFun_finset { n } ( Finset.range n ) ; simp_all +decide [ Set.subset_def, iIndepFun ] ;
  rw [ ProbabilityTheory.indepFun_iff_measure_inter_preimage_eq_mul ] at *;
  intro s t hs ht; specialize this ( ( fun f => Real.exp ( R * f ⟨ n, by simp +decide ⟩ ) ) ⁻¹' t ) ( ( fun f => Real.exp ( R * ∑ k : ↥ ( Finset.range n ), f k ) ) ⁻¹' s ) ; simp_all +decide [ Set.preimage ] ;
  convert this _ _ using 1;
  · rw [ Set.inter_comm ];
    congr! 3;
    ext x; rw [ ← Finset.sum_attach ] ;
  · rw [ mul_comm ];
    congr! 3;
    ext x; rw [ ← Finset.sum_attach ] ;
  · exact measurableSet_preimage ( measurable_id'.exp.comp ( measurable_const.mul ( measurable_pi_apply _ ) ) ) ht |> MeasurableSet.mem;
  · exact MeasurableSet.mem ( hs.preimage ( Real.continuous_exp.measurable.comp ( measurable_const.mul ( Finset.measurable_sum _ fun i _ => measurable_pi_apply i ) ) ) )

/-! ## Adaptedness of the exponential process -/

/-
The exponential process `exp(R * ∑_{k<n} Z_k)` is strongly adapted to the
    natural filtration `F_n = ⨆_{k<n} σ(Z_k)`.
-/
lemma expProcess_stronglyAdapted
    {Z : ℕ → Ω → ℝ} {R : ℝ}
    (hZ_meas : ∀ k, Measurable (Z k)) :
    StronglyAdapted (incrementFiltration Z hZ_meas)
      (fun n ω => Real.exp (R * ∑ k ∈ Finset.range n, Z k ω)) := by
  intro n;
  refine' Measurable.stronglyMeasurable _;
  refine' Measurable.exp ( Measurable.const_mul _ _ );
  refine' Finset.measurable_sum _ fun k hk => _;
  refine' Measurable.of_comap_le _;
  exact le_iSup₂ ( f := fun k _ => MeasurableSpace.comap ( Z k ) measurableSpace ) k hk

/-! ## Conditional expectation inequality -/

/-
The past and future σ-algebras are independent, i.e.,
    `⨆_{k < i} σ(Z_k)` is independent of `⨆_{k ∈ Ico i j} σ(Z_k)`.
-/
lemma past_future_indep
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {Z : ℕ → Ω → ℝ}
    (hZ_meas : ∀ k, Measurable (Z k))
    (h_Z_indep : iIndepFun Z μ)
    (i j : ℕ) (hij : i ≤ j) :
    Indep (⨆ k ∈ Finset.range i, MeasurableSpace.comap (Z k) (borel ℝ))
          (⨆ k ∈ Finset.Ico i j, MeasurableSpace.comap (Z k) (borel ℝ)) μ := by
  apply_rules [ ProbabilityTheory.indep_iSup_of_disjoint ];
  · exact fun k => Measurable.comap_le ( hZ_meas k );
  · simp +decide [ Finset.disjoint_left, Set.disjoint_left ];
    exact fun k hk₁ hk₂ => not_lt_of_ge ( Finset.mem_Ico.mp hk₂ |>.1 ) ( Multiset.mem_range.mp hk₁ )

/-
The integral of the exponential over an `Ico` block equals 1.
-/
lemma integral_exp_sum_Ico_eq_one
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {Z : ℕ → Ω → ℝ} {R : ℝ}
    (hZ_meas : ∀ k, Measurable (Z k))
    (h_Z_id : ∀ i, IdentDistrib (Z i) (Z 0) μ μ)
    (h_Z_indep : iIndepFun Z μ)
    (h_Z_int : ∀ n, Integrable (fun ω => Real.exp (R * Z n ω)) μ)
    (hR_def : ∫ ω, Real.exp (R * Z 0 ω) ∂μ = 1)
    (i j : ℕ) :
    ∫ ω, Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω) ∂μ = 1 := by
  have h_gauss_prod : ∫ ω, ∏ k ∈ Finset.Ico i j, Real.exp (R * (Z k ω)) ∂μ = ∏ k ∈ Finset.Ico i j, ∫ ω, Real.exp (R * (Z k ω)) ∂μ := by
    have h_prod : ∀ {s : Finset ℕ}, (∀ k ∈ s, AEMeasurable (fun ω => Real.exp (R * Z k ω)) μ) → (∫ ω, ∏ k ∈ s, Real.exp (R * Z k ω) ∂μ) = ∏ k ∈ s, ∫ ω, Real.exp (R * Z k ω) ∂μ := by
      intro s hs; induction s using Finset.induction <;> simp_all +decide [ MeasureTheory.integral_const_mul ] ;
      rename_i k s hk hs;
      have h_indep : ProbabilityTheory.IndepFun (fun ω => Real.exp (R * Z k ω)) (fun ω => ∏ k ∈ s, Real.exp (R * Z k ω)) μ := by
        have h_indep : ProbabilityTheory.IndepFun (fun ω => Z k ω) (fun ω => (fun k => Z k ω) : Ω → (s → ℝ)) μ := by
          have := h_Z_indep.indepFun_finset s;
          specialize this { k } ; simp_all +decide [ ProbabilityTheory.IndepFun ];
          rw [ Kernel.indepFun_iff_measure_inter_preimage_eq_mul ] at *;
          intro s_1 t hs_1 ht; specialize this t ( ( fun x => x ⟨ k, by simp +decide ⟩ ) ⁻¹' s_1 ) ht ( by measurability ) ; simp_all +decide [ Set.preimage ] ;
          rw [ Set.inter_comm, this, mul_comm ];
        convert h_indep.comp ( Measurable.exp ( measurable_const.mul measurable_id' ) ) ( show Measurable fun x : s → ℝ => ∏ k : s, Real.exp ( R * x k ) from ?_ ) using 1;
        · ext ω; simp +decide [ Finset.prod_apply ] ;
          conv_lhs => rw [ ← Finset.prod_attach ] ;
        · exact Finset.measurable_prod _ fun _ _ => Measurable.exp ( measurable_const.mul ( measurable_pi_apply _ ) );
      rw [ ← ‹∫ ω, ∏ k ∈ s, Real.exp ( R * Z k ω ) ∂μ = ∏ k ∈ s, ∫ ω, Real.exp ( R * Z k ω ) ∂μ› ];
      apply_rules [ ProbabilityTheory.IndepFun.integral_mul_eq_mul_integral ];
      · exact hs.1.aestronglyMeasurable;
      · fun_prop;
    exact h_prod fun k hk => ( h_Z_int k |> Integrable.aemeasurable );
  simp_all +decide [ Finset.mul_sum _ _ _, Real.exp_sum ];
  exact Finset.prod_eq_one fun k hk => by rw [ show ∫ ω, Real.exp ( R * Z k ω ) ∂μ = 1 from by simpa [ hR_def ] using mgf_eq_one_all hR_def h_Z_id h_Z_int k ] ;

/-
The conditional expectation of the exponential process satisfies the
    supermartingale inequality: `E[M_j | F_i] ≤ M_i` a.e. for `i ≤ j`.
    This follows from the product decomposition and independence of future increments.
-/
lemma expProcess_condExp_le
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {Z : ℕ → Ω → ℝ} {R : ℝ}
    (hR_pos : 0 < R)
    (hZ_meas : ∀ k, Measurable (Z k))
    (h_Z_id : ∀ i, IdentDistrib (Z i) (Z 0) μ μ)
    (h_Z_indep : iIndepFun Z μ)
    (h_Z_int : ∀ n, Integrable (fun ω => Real.exp (R * Z n ω)) μ)
    (hR_def : ∫ ω, Real.exp (R * Z 0 ω) ∂μ = 1) :
    ∀ (i j : ℕ), i ≤ j →
      μ[(fun n ω => Real.exp (R * ∑ k ∈ Finset.range n, Z k ω)) j |
        (incrementFiltration Z hZ_meas).seq i] ≤ᶠ[ae μ]
      (fun n ω => Real.exp (R * ∑ k ∈ Finset.range n, Z k ω)) i := by
  intro i j hij
  have h_cond_exp : ∀ᵐ ω ∂μ, (μ[(fun n ω => Real.exp (R * ∑ k ∈ Finset.range n, Z k ω)) j | (incrementFiltration Z hZ_meas) i] ω) = (fun n ω => Real.exp (R * ∑ k ∈ Finset.range n, Z k ω)) i ω * (μ[(fun ω => Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω)) | (incrementFiltration Z hZ_meas) i] ω) := by
    have h_cond_exp : ∀ᵐ ω ∂μ, (μ[(fun n ω => Real.exp (R * ∑ k ∈ Finset.range n, Z k ω)) j | (incrementFiltration Z hZ_meas) i] ω) = (μ[(fun n ω => Real.exp (R * ∑ k ∈ Finset.range i, Z k ω)) i * (fun ω => Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω)) | (incrementFiltration Z hZ_meas) i] ω) := by
      simp +decide [ ← Real.exp_add, mul_add, Finset.sum_Ico_eq_sub _ hij ];
      exact Filter.Eventually.of_forall fun ω => by congr; ext; rw [ Pi.mul_apply, ← Real.exp_add ] ; ring;
    have h_cond_exp : MeasureTheory.Integrable (fun ω => (fun n ω => Real.exp (R * ∑ k ∈ Finset.range i, Z k ω)) i ω * (fun ω => Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω)) ω) μ := by
      convert expProcess_integrable h_Z_indep hZ_meas h_Z_int j using 1;
      ext ω; rw [ ← Real.exp_add ] ; rw [ ← mul_add, ← Finset.sum_range_add_sum_Ico _ hij ] ;
    have h_cond_exp : MeasureTheory.Integrable (fun ω => (fun ω => Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω)) ω) μ := by
      have := integral_exp_sum_Ico_eq_one hZ_meas h_Z_id h_Z_indep h_Z_int hR_def i j;
      exact MeasureTheory.integrable_of_integral_eq_one this;
    have h_cond_exp : ∀ᵐ ω ∂μ, (μ[(fun n ω => Real.exp (R * ∑ k ∈ Finset.range i, Z k ω)) i * (fun ω => Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω)) | (incrementFiltration Z hZ_meas) i] ω) = (fun n ω => Real.exp (R * ∑ k ∈ Finset.range i, Z k ω)) i ω * (μ[(fun ω => Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω)) | (incrementFiltration Z hZ_meas) i] ω) := by
      apply_rules [ MeasureTheory.condExp_mul_of_stronglyMeasurable_left ];
      exact Pythia.expProcess_stronglyAdapted hZ_meas i;
    filter_upwards [ ‹∀ᵐ ω ∂μ, μ[(fun n ω => Real.exp (R * ∑ k ∈ range n, Z k ω)) j | (incrementFiltration Z hZ_meas) i] ω = μ[(fun n ω => Real.exp (R * ∑ k ∈ range i, Z k ω)) i * fun ω => Real.exp (R * ∑ k ∈ Ico i j, Z k ω) | (incrementFiltration Z hZ_meas) i] ω›, h_cond_exp ] with ω hω₁ hω₂ using hω₁.trans hω₂;
  have h_cond_exp_g : ∀ᵐ ω ∂μ, (μ[(fun ω => Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω)) | (incrementFiltration Z hZ_meas) i] ω) = (∫ ω, Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω) ∂μ) := by
    have h_cond_exp_g : Indep (⨆ k ∈ Finset.range i, MeasurableSpace.comap (Z k) (borel ℝ)) (⨆ k ∈ Finset.Ico i j, MeasurableSpace.comap (Z k) (borel ℝ)) μ := by
      apply_rules [ past_future_indep ];
    have h_cond_exp_g : StronglyMeasurable[⨆ k ∈ Finset.Ico i j, MeasurableSpace.comap (Z k) (borel ℝ)] (fun ω => Real.exp (R * ∑ k ∈ Finset.Ico i j, Z k ω)) := by
      have h_cond_exp_g : ∀ k ∈ Finset.Ico i j, Measurable[⨆ k ∈ Finset.Ico i j, MeasurableSpace.comap (Z k) (borel ℝ)] (fun ω => Z k ω) := by
        intro k hk;
        apply_rules [ Measurable.of_comap_le ];
        simp +decide [ MeasurableSpace.comap_id ];
        exact le_iSup₂_of_le k ( Finset.mem_Ico.mp hk ) le_rfl;
      exact Measurable.stronglyMeasurable ( by measurability );
    convert MeasureTheory.condExp_indep_eq _ _ _ _;
    exact ⨆ k ∈ Finset.Ico i j, MeasurableSpace.comap ( Z k ) ( borel ℝ );
    exact iSup_le fun k => iSup_le fun hk => MeasurableSpace.comap_le_iff_le_map.mpr ( hZ_meas k );
    exact (incrementFiltration Z hZ_meas).le' i;
    · infer_instance;
    · exact h_cond_exp_g;
    · grind +suggestions;
  filter_upwards [ h_cond_exp, h_cond_exp_g ] with ω hω₁ hω₂ using by rw [ hω₁, hω₂, integral_exp_sum_Ico_eq_one hZ_meas h_Z_id h_Z_indep h_Z_int hR_def ] ; simp +decide ;

/-! ## Key supermartingale property -/

/-- **The exponential tilting process is a supermartingale.**

For iid random variables `Z_k` with `E[exp(R·Z_k)] = 1`, the process
`M_n = exp(R · ∑_{k<n} Z_k)` is a supermartingale w.r.t. the natural filtration.

This combines:
- Multiplicative decomposition: `M_{n+1} = M_n · exp(R·Z_{n+1})`
- Pull-out property: `E[M_n · g | F_n] = M_n · E[g | F_n]`
- Independence: `E[exp(R·Z_{n+1}) | F_n] = E[exp(R·Z_{n+1})] = 1`
-/
lemma expProcess_supermartingale
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    {T X : ℕ → Ω → ℝ} {c R : ℝ}
    (hR_pos : 0 < R)
    (hR_def : ∫ ω, Real.exp (R * (X 0 ω - c * T 0 ω)) ∂μ = 1)
    (hT_meas : ∀ i, Measurable (T i))
    (hX_meas : ∀ i, Measurable (X i))
    (h_Z_id : ∀ i, IdentDistrib (fun ω => X i ω - c * T i ω)
                                  (fun ω => X 0 ω - c * T 0 ω) μ μ)
    (h_Z_indep : iIndepFun (fun (i : ℕ) (ω : Ω) => X i ω - c * T i ω) μ)
    (h_Z_int : ∀ n, Integrable
      (fun ω => Real.exp (R * (X n ω - c * T n ω))) μ) :
    ∃ (𝓕 : Filtration ℕ mΩ),
      Supermartingale
        (fun n ω => Real.exp (R * ∑ k ∈ Finset.range n, (X k ω - c * T k ω)))
        𝓕 μ := by
  -- Use the natural filtration generated by Z_k = X_k - c*T_k
  set Z : ℕ → Ω → ℝ := fun k ω => X k ω - c * T k ω with hZ_def
  have hZ_meas : ∀ k, Measurable (Z k) := fun k =>
    (hX_meas k).sub ((hT_meas k).const_mul c)
  refine ⟨incrementFiltration Z hZ_meas, ?_, ?_, ?_⟩
  · -- StronglyAdapted: M_n is adapted to F_n
    exact expProcess_stronglyAdapted hZ_meas
  · -- Conditional expectation: μ[M_j | F_i] ≤ᵐ M_i for i ≤ j
    exact expProcess_condExp_le hR_pos hZ_meas h_Z_id h_Z_indep h_Z_int hR_def
  · -- Integrability
    intro n
    exact expProcess_integrable h_Z_indep hZ_meas h_Z_int n

/-! ## Main theorem -/

/-- **Sparre Andersen Ruin Bound (Lundberg's Inequality for Renewal Models).**

In the Sparre Andersen renewal risk model with iid inter-arrival times
(not necessarily exponential) and iid claim sizes, the ruin probability
satisfies `ψ(u) ≤ exp(-R·u)` where `R` is the adjustment coefficient.

**Modifications from the original proposed signature:**
- `iIndepFun` replaces `iIndepFun (fun _ => mΩ.borel ℝ)` (Mathlib infers codomain σ-algebra).
- Added measurability, identical-distribution, joint independence, and integrability hypotheses.

**References.** Sparre Andersen (1957); Asmussen–Albrecher Ch. VI. -/
theorem sparre_andersen_ruin
    {Ω : Type*} [mΩ : MeasurableSpace Ω]
    {μ : Measure Ω} [IsProbabilityMeasure μ]
    (u : ℝ) (hu : 0 ≤ u)
    {T : ℕ → Ω → ℝ}
    {X : ℕ → Ω → ℝ}
    (h_T_iid : iIndepFun T μ)
    (h_T_pos : ∀ i ω, 0 < T i ω)
    (h_X_iid : iIndepFun X μ)
    (h_X_pos : ∀ i ω, 0 ≤ X i ω)
    (h_indep : ∀ i j, IndepFun (T i) (X j) μ)
    (c : ℝ) (hc : 0 < c)
    (h_safety : ∫ ω, X 0 ω ∂μ < c * ∫ ω, T 0 ω ∂μ)
    (R : ℝ) (hR_pos : 0 < R)
    (hR_def : ∫ ω, Real.exp (R * (X 0 ω - c * T 0 ω)) ∂μ = 1)
    -- Additional formalization hypotheses:
    (hT_meas : ∀ i, Measurable (T i))
    (hX_meas : ∀ i, Measurable (X i))
    (h_Z_id : ∀ i, IdentDistrib (fun ω => X i ω - c * T i ω)
                                  (fun ω => X 0 ω - c * T 0 ω) μ μ)
    (h_Z_indep : iIndepFun (fun (i : ℕ) (ω : Ω) => X i ω - c * T i ω) μ)
    (h_Z_int : ∀ n, Integrable
      (fun ω => Real.exp (R * (X n ω - c * T n ω))) μ) :
    let ψ : ℝ → ℝ := sparreAndersenRuinProb X T c μ
    ψ u ≤ Real.exp (-R * u) := by
  intro ψ
  show sparreAndersenRuinProb X T c μ u ≤ Real.exp (-R * u)
  unfold sparreAndersenRuinProb
  -- Step 1: Obtain the supermartingale from the key lemma
  obtain ⟨𝓕, hsup⟩ := expProcess_supermartingale hR_pos hR_def hT_meas hX_meas
    h_Z_id h_Z_indep h_Z_int
  -- Step 2: M₀ = 1 a.s.
  have hunit : ∀ᵐ ω ∂μ,
      Real.exp (R * ∑ k ∈ Finset.range 0, (X k ω - c * T k ω)) = 1 := by
    filter_upwards with ω; simp [mul_zero, Real.exp_zero]
  -- Step 3: Apply Ville's inequality with threshold exp(R·u)
  have hexp_pos : (0 : ℝ) < Real.exp (R * u) := Real.exp_pos _
  have hville := ville_supermartingale_unit_initial hsup
    (fun t ω => Real.exp_nonneg _) hunit hexp_pos
  -- Step 4: The ruin event ⊆ the exponential event
  have hsub := ruin_subset_exp_event X T c R u hR_pos
  -- Step 5: Measure monotonicity + Ville bound
  have hmeas_le : μ {ω | ∃ n, ∑ k ∈ Finset.range n, (X k ω - c * T k ω) > u} ≤
      ↑(1 / Real.exp (R * u)).toNNReal :=
    le_trans (measure_mono hsub) hville
  -- Step 6: Convert ENNReal inequality to ℝ
  have h6 : (μ {ω | ∃ n, ∑ k ∈ range n, (X k ω - c * T k ω) > u}).toReal ≤
      (↑(1 / Real.exp (R * u)).toNNReal : ENNReal).toReal :=
    ENNReal.toReal_mono ENNReal.coe_ne_top hmeas_le
  -- Step 7: Simplify RHS to exp(-R*u)
  have h7 : (↑(1 / Real.exp (R * u)).toNNReal : ENNReal).toReal = Real.exp (-R * u) := by
    change NNReal.toReal _ = _
    rw [Real.toNNReal_of_nonneg (by positivity)]
    simp [Real.exp_neg, neg_mul]
  linarith

end Pythia